import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header"
import Banner from "../components/Banner"
import Main from "../components/Main"
import SmallCard from "../components/SmallCard"
import MediumCard from '../components/MediumCard'
import BigCard from '../components/BigCard'
import Footer from '../components/Footer'

export default function Home({ exploreData,exploreSecondData }) {
  return (
    <div className="">
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/* Header */}
      <Header />
      {/* Banner */}
      <Banner />
      {/* Main */}
      <section className='max-w-7xl px-8 sm:px-16 py-20  mx-auto pt-6'>
        <h2 className='text-4xl font-semibold pb-5 '>Explore nearby</h2>
        <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
          {exploreData.map(item => (
            <div key={item.location}>
              <SmallCard
                key={item.location}
                img={item.img}
                location={item.location}
                distance={item.distance}
              />
            </div>
          ))}
        </div>
      </section>
      <section className='max-w-7xl px-8 sm:px-16 py-20  mx-auto pt-6'>
        <h2 className='text-4xl font-semibold py-8 '>Live anyware</h2>
        <div className='flex items-center space-x-3 overflow-scroll scrollbar-hide py-5 px-3 -ml-3 -mt-5'>
          {exploreSecondData.map(item => (
            <div key={item.title}>
              <MediumCard
                key={item.title}
                img={item.img}
                title={item.title}
              />
            </div>
          ))}
        </div>
      </section> 
     
        <BigCard
          img="https://links.papareact.com/4cj"
          title="The greatest outdoors"
          description="Wishlist cerated by Airbnb."
          buttonText="Get inspired"
        />
        <Main/>
     

      
      {/* Footer */}
      <Footer />


    </div>
  )
}

export async function getStaticProps(context) {
  const exploreData = await fetch('https://links.papareact.com/pyp').then(result => result.json());
  const exploreSecondData = await fetch('https://links.papareact.com/zp1').then(result => result.json());
  return {
    props: {
      exploreData: exploreData,
      exploreSecondData:exploreSecondData,
    }
  }
}
